class Constants:
    link_site = 'http://automationpractice.com/index.php'
    EMAIL = 'felahek839@ukgent.com'
    PASSWORD = 'october'
    NAME_USER = 'Jaide Saford'
    CHECKING_COLOR_BLACK = 'black'
    SIZE_M = 'M'
    EXPECTED_COLORS_AND_SIZE_OF_BLOUSE = 'Black, M'
    EXPECTED_TEXT_ABOUT_ADDING_ITEMS = "successfully added"
    NUMBER_OF_ITEMS_IN_CART = "2"
    NUMBER_OF_DRESSES_IN_CART = "2"
    CHECKING_MIDI_DRESS = 'Midi Dress'
    EXPECTED_COLORS_AND_SIZE_OF_DRESS = 'Green, M'
    INFO_ABOUT_ORDER = 'Your order on My Store is complete.'
    STATUS_ORDER_TEXT = 'On backorder'
    ADDED_TO_WISHLIST = 'Added to your wishlist.'
    QUANTITY_ITEMS_IN_WISHLIST = '3'
    OPTION_QUANTITY_OF_ITEM_IN_WISHLIST = '3'
    CHANGED_QUANTITY_ITEMS_IN_WISHLIST = '4'
    PRIORITY_HIGH = 'HIGH'
